### ISSUE TITLE
Implement https://channels.readthedocs.io/en/stable/getting-started.html

### ISSUE THREAD

**Issue by dkdndes** [sabisasam/django-tutorial#15]
- [x] [https://yuml.me/](Draw a UML diagram) which enables us to see the participants in a WebSocket communication
- [x] Upload the result to github 

Please have also a look at 
* https://blog.heroku.com/in_deep_with_django_channels_the_future_of_real_time_apps_in_django
* https://channels.readthedocs.io/en/stable/javascript.html#channels-websocket-wrapper
* https://github.com/andrewgodwin/channels-examples/tree/master/databinding

- [ ] Compile a list of questions you might have ... 
- [x] Don't forget to document your progress

**Comment by sabisasam** [comment]
What exactly do you expect from the UML diagram? I don't quite know how I should start with it.

**Comment by dkdndes** [comment]
Start with which you would use for what, then decide which makes sense for a user (in this case a developer) in the context of the tutorial.
__ 
Sent from my iPhone If you would like to discuss, please call me on +49(0)176-5325-8535

**Comment by sabisasam** [comment]
Agreed that the UML diagram will be done later.
