### ISSUE TITLE
Apply "git tagging"

### ISSUE THREAD

**Issue by dkdndes** [sabisasam/django-tutorial#4]
Please read [Git-Basics-Tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and apply it against each branch separate.

Special: "Annotated Tags" and how to create an annotated tag 

     $ git tag -a v1.0.0 -m "my tutorial 1.0.0"

and then read about "Semantic Versioning" and what the 3rd digit means. 

Semantic Versioning[1] is a formal convention for specifying compatibility using a three-part version number: 
* major version; 
* minor version; and 
* patch. 

The patch number (3rd) is incremented (any size, not just till "9") for minor changes and bug fixes which do not change the software's application or application programming interface (API). 

[1] https://www.sitepoint.com/semantic-versioning-why-you-should-using/

**Comment by sabisasam** [comment]
Finished reading and added annotated tags.
