### ISSUE TITLE
Generate a mookup of the current project and upload the result to the repository

### ISSUE THREAD

**Issue by dkdndes** [sabisasam/django-tutorial#5]
## What is a mock up screens?
In manufacturing and design, a mockup, or mock-up, is a scale or full-size model of a design or device, used for teaching, demonstration, design evaluation, promotion, and other purposes. A mockup is a prototype if it provides at least part of the functionality of a system and enables testing of a design.

Please, use 

* [Pencil for Mookups](http://pencil.evolus.vn/Features.html)

and upload the pictures in a docs directory below "/".

**Comment by sabisasam** [comment]
Are the mockups okay or should I change something?
