### ISSUE TITLE
Create a .gitignore file

### ISSUE THREAD

**Issue by dkdndes** [sabisasam/django-tutorial#6]
Please check github.com/django/django for a template and use it here. Explain: Whats the purpose of the file?

**Comment by sabisasam** [comment]
https://github.com/django/django/blob/master/.gitignore

The .gitignore file specifies which files Git should ignore.

In this case, for example:
* The pattern `*.pot` would match `foo.pot`, `.pot` and `items/foo.pot`.
* The pattern `*.py[co]` is shorter for patterns `*.pyc` and `*.pyo`.
* The pattern `.tox/` would match `.tox/foo.bar`, `.tox/logs/foo.bar`, `items/.tox/foo.bar` and `items/.tox/logs/foo.bar`.
* The pattern `__pycache__` would match `__pycache__`, `__pycache__/foo.bar`, `__pycache__/items/foo.bar`, `items/__pycache__` and `items/__pycache__/foo.bar`.
* The pattern `tests/.coverage` would match `tests/.coverage` but not `.coverage` or `items/tests/.coverage`.

If a file matches, it will be ignored.

**Comment by dkdndes** [comment]
Close #6 <- will close the issue with the next merge. Please try a merge of a branch and see for yourself.

* https://help.github.com/articles/closing-issues-using-keywords/
