### ISSUE TITLE
Introduce custom permissions for all models

### ISSUE THREAD

**Issue by dkdndes** [sabisasam/django-tutorial#8]
As a User I like to see selfspeaking permissions which guide me through the workflow of my application. For that reason read the documentation about [custom-permissions](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#custom-permissions). 

After completion introduce in all classes self-speaking permissions (you find useable) and check in /admin where you find them. Do a screen-shoot and explain in a comment the meaning of it.

**Comment by sabisasam** [comment]
![permissions](https://user-images.githubusercontent.com/29835746/29516109-68e46622-866f-11e7-9026-19c5b8df3d4e.jpg)

The permissions in the "Chosen permissions" box were added.

If a user tries to e.g. view an unpublished question, it should be checked with `user.has_perm('polls.view_unpublished_question')` if the user has permission to do so. In case it returns `True`, the user can view those questions. But if it returns `False`, the permission was not given.

**Comment by dkdndes** [comment]
Please, add (and explain) the following to your permission handling. Do you need to adjust something?

* http://django-extensions.readthedocs.io/en/latest/command_signals.html#custom-permissions-for-all-models

```
from django.db.models.signals import post_syncdb
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission
from django_extensions.management.signals import post_command
from django_extensions.management.commands.update_permissions import Command as UpdatePermissionsCommand

def add_permissions(sender, **kwargs):
  """
  Add view and list permissions to all content types.
  """
  # for each of our content types
  for content_type in ContentType.objects.all():

    for action in ['view', 'list']:
      # build our permission slug
      codename = "%s_%s" % (action, content_type.model)

      try:
        Permission.objects.get(content_type=content_type, codename=codename)
        # Already exists, ignore
      except Permission.DoesNotExist:
        # Doesn't exist, add it
        Permission.objects.create(content_type=content_type,
                      codename=codename,
                      name="Can %s %s" % (action, content_type.name))
        print "Added %s permission for %s" % (action, content_type.name)
post_command.connect(add_permissions, UpdatePermissionsCommand)

```

**Comment by sabisasam** [comment]
I had to adjust some outdated things like the use of `print` and `post_syncdb`. And the way how the imports from django_extensions were used in here doesn't seem to work anymore.

The function add_permissions gets called when the post_migrate signal is caused. This happens through `python manage.py migrate`. Then the function checks for each content type whether a view and list permission already exist. If they don't, the function creates those missing permissions. Otherwise nothing happens. To see which permissions got created, there is a print function after the permission creation part.
